const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const manifest = JSON.parse(read('zotero/manifest.json'));
assert.equal(manifest.applications.zotero.id, 'researchflow@groele.org');
assert(!manifest.background && !manifest.content_scripts && !manifest.host_permissions);
for (const p of ['manifest.json','scripts/background.js','scripts/content.js','scripts/journal-portals.js','scripts/scholar-mirrors.js']) assert(!fs.existsSync(path.join(root,p)), 'Chrome-only entrypoint must be absent: '+p);
assert(fs.readdirSync(path.join(root,'dist-zip')).every(p=>p.endsWith('.xpi')), 'release artifacts must be Zotero XPI files');
const html = read('pages/options.html');
for (const match of html.matchAll(/<script\s+src="([^"]+)"/g)) assert(fs.existsSync(path.resolve(root,'pages',match[1])), 'missing script: '+match[1]);
for (const id of ['view-dashboard','view-manuscripts','view-submissions','view-settings','journal-portals-list','btn-export-db','btn-sync-cloud-now']) assert(html.includes('id="'+id+'"'));
assert(!html.includes('submission-assist-enabled'));
const options=read('scripts/options.js');
assert(!options.includes('consumePendingAcademicDraft') && !options.includes('consumePendingSubmissionDraft'));
assert(!/\bchrome\./.test(options));
const storage=read('scripts/storage.js');
assert(storage.includes('zotero.ResearchFlow.saveDatabase(normalized)'));
assert(!storage.includes("action: 'SAVE_DATABASE'") && !storage.includes('triggerBackgroundSync'));
assert(storage.includes('filterDeletedEntities') && storage.includes('shouldRunCloudSync(this.cache)'));
console.log('Zotero runtime contract tests passed');
